import Audio from '@/models/audio-model';
import AutoGeneratedPlaylist from '@/models/auto-generated-playlist-model';
import cron from 'node-cron';

// The five fields in the cron syntax represent (in order) minutes, hours, day of the month, month, and day of the week.

// cron.schedule("*/2 * * * * *", () => {
//   console.log("I am running every 2 seconds!");
// });

// playlist: {title: , items: []}
const generatedPlaylist = async () => {
	const result = await Audio.aggregate([
		{ $sort: { likes: -1 } },
		{
			$sample: { size: 20 },
		},
		{
			$group: {
				_id: '$category',
				audios: { $push: '$$ROOT._id' },
			},
		},
	]);

	result.map(async (item) => {
		await AutoGeneratedPlaylist.updateOne(
			{ title: item._id },
			{ $set: { items: item.audios } },
			{ upsert: true }
		);
	});
};

cron.schedule('0 0 * * *', async () => {
	// Run every 24 hrs
	await generatedPlaylist();
});
